// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-fnmyeKbsFacX0OjrtEZmlDT-a9wQIqY',
    appId: '1:1051900210441:web:569a26d23895bab3bcb7d8',
    messagingSenderId: '1051900210441',
    projectId: 'notificacoes-app-c227b',
    authDomain: 'notificacoes-app-c227b.firebaseapp.com',
    storageBucket: 'notificacoes-app-c227b.firebasestorage.app',
    measurementId: 'G-6V4T4FEVW1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmGReeHQtvC0QrrFmPJNsWjhfgT3ro9fk',
    appId: '1:1051900210441:android:1473e77818b29722bcb7d8',
    messagingSenderId: '1051900210441',
    projectId: 'notificacoes-app-c227b',
    storageBucket: 'notificacoes-app-c227b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyy9Z7XRhA1NcVkX0uNWms3YaAJsrW7NU',
    appId: '1:1051900210441:ios:5b108cd845560e82bcb7d8',
    messagingSenderId: '1051900210441',
    projectId: 'notificacoes-app-c227b',
    storageBucket: 'notificacoes-app-c227b.firebasestorage.app',
    iosBundleId: 'com.example.quermesseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-fnmyeKbsFacX0OjrtEZmlDT-a9wQIqY',
    appId: '1:1051900210441:web:231773bd01117029bcb7d8',
    messagingSenderId: '1051900210441',
    projectId: 'notificacoes-app-c227b',
    authDomain: 'notificacoes-app-c227b.firebaseapp.com',
    storageBucket: 'notificacoes-app-c227b.firebasestorage.app',
    measurementId: 'G-TF27DXZ7HG',
  );
}
